apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccount
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: {{ .Values.projectId }}
  labels:
    {{- include "app-chart.labels" . | nindent 4 }}
  name: {{ include "app-chart.serviceAccountName" . }}
