apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: {{ include "app-chart.fullname" . }}-wi
  labels:
      {{- include "app-chart.labels" . | nindent 4 }}
spec:
  member: "serviceAccount:{{ .Values.projectId }}.svc.id.goog[{{ .Release.Namespace }}/{{ include "app-chart.serviceAccountName" . }}]"
  role: roles/iam.workloadIdentityUser
  resourceRef:
    apiVersion: iam.cnrm.cloud.google.com/v1beta1
    kind: IAMServiceAccount
    name: {{ include "app-chart.serviceAccountName" . }}
